[profile.default]
src = "contracts"
test = "test"
out = "out"
libs = ["lib"]
solc = "0.8.20"
exclude = ["contracts/legacy/**", "**/WETH.sol"]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@uniswap/v2-periphery/=lib/v2-periphery/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "forge-std/=lib/forge-std/src/"
]